openapi: 3.2.0
info:
  title: Settings Multicurrency Exchange rates API
  description: Basepom for all HubSpot Projects
  version: 2026-09
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
    commerce: FREE
    crmHub: FREE
    dataHub: FREE
servers:
- url: https://api.hubapi.com
tags:
- name: Exchange Rates
paths:
  /settings/currencies/2026-09/exchange-rates:
    get:
      tags:
      - Exchange Rates
      summary: Get exchange rates
      description: Get a list of exchange rates
      operationId: get-/settings/currencies/2026-09/exchange-rates
      security:
      - oauth2:
        - cpq.quotes.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - settings.currencies.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - cpq.quotes.read
    post:
      tags:
      - Exchange Rates
      summary: Add a new exchange rate
      description: Create a new exchange rate with specified conversion rate and currency codes.
      operationId: post-/settings/currencies/2026-09/exchange-rates
      security:
      - oauth2:
        - settings.currencies.write
  /settings/currencies/2026-09/exchange-rates/current:
    get:
      tags:
      - Exchange Rates
      summary: Get all current exchange rates
      description: Retrieve all current exchange rates for all currency pairs.
      operationId: get-/settings/currencies/2026-09/exchange-rates/current
      security:
      - oauth2:
        - cpq.quotes.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - settings.currencies.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - cpq.quotes.read
  /settings/currencies/2026-09/exchange-rates/update-visibility:
    post:
      tags:
      - Exchange Rates
      summary: Change the visibility of a specific currency pairs
      description: Change the visibility setting for a currency pair. This will hide or display a currency pair for users in the HubSpot app.
      operationId: post-/settings/currencies/2026-09/exchange-rates/update-visibility
      security:
      - oauth2:
        - settings.currencies.write
  /settings/currencies/2026-09/exchange-rates/{exchangeRateId}:
    get:
      tags:
      - Exchange Rates
      summary: Get the details for a specific exchange rate
      description: Retrieve the details for a specific exchange rate specified by its ID.
      operationId: get-/settings/currencies/2026-09/exchange-rates/{exchangeRateId}
      security:
      - oauth2:
        - cpq.quotes.write
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - settings.currencies.read
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - cpq.quotes.read
    patch:
      tags:
      - Exchange Rates
      summary: Update a conversion rate
      description: Update an existing conversion rate, specified by its ID.
      operationId: patch-/settings/currencies/2026-09/exchange-rates/{exchangeRateId}
      security:
      - oauth2:
        - settings.currencies.write
components:
  securitySchemes:
    developer_hapikey:
      type: apiKey
      name: hapikey
      in: query
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            cpq.quotes.write: ''
            settings.currencies.write: ''
    private_apps:
      type: apiKey
      name: private-app
      in: header
    private_apps_legacy:
      type: apiKey
      name: private-app-legacy
      in: header
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
  commerce: FREE
  crmHub: FREE
  dataHub: FREE
