openapi: 3.0.1
info:
  title: HubSpot CRM Courses
  description: Basepom for all HubSpot Projects
  version: 2026-03
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
    commerce: FREE
    crmHub: FREE
    dataHub: FREE
  x-hubspot-introduction: Use the courses API to create and manage CRM records that represent information
    about a structured program or series of lessons, trainings, or educational modules. Identify the course
    object type with its object type ID 0-410
servers:
- url: https://api.hubapi.com
tags:
- name: Advanced
- name: Basic
- name: Batch
- name: Search
paths:
  /crm/objects/2026-03/0-410:
    get:
      tags:
      - Basic
      summary: Retrieve courses
      description: Read a page of courses. Control what is returned via the `properties` query param.
      operationId: get-/crm/objects/2026-03/0-410
      security:
      - oauth2:
        - crm.objects.courses.read
      x-hubspot-user-level-auth:
        internalOnly: false
    post:
      tags:
      - Basic
      summary: Create a course
      description: Create a course with the given properties and return a copy of the object, including
        the ID. Documentation and examples for creating standard courses is provided.
      operationId: post-/crm/objects/2026-03/0-410
      security:
      - oauth2:
        - crm.objects.courses.write
      x-hubspot-user-level-auth:
        internalOnly: false
  /crm/objects/2026-03/0-410/batch/archive:
    post:
      tags:
      - Batch
      summary: Batch archive courses
      description: Archive a batch of objects
      operationId: post-/crm/objects/2026-03/0-410/batch/archive
      security:
      - oauth2:
        - crm.objects.courses.write
      x-hubspot-user-level-auth:
        internalOnly: false
  /crm/objects/2026-03/0-410/batch/create:
    post:
      tags:
      - Batch
      summary: Batch create courses
      description: Create a batch of objects
      operationId: post-/crm/objects/2026-03/0-410/batch/create
      security:
      - oauth2:
        - crm.objects.courses.write
      x-hubspot-user-level-auth:
        internalOnly: false
  /crm/objects/2026-03/0-410/batch/read:
    post:
      tags:
      - Batch
      summary: Batch retrieve courses
      description: 'Retrieve records by record ID or include the `idProperty` parameter to retrieve records
        by a custom unique value property. '
      operationId: post-/crm/objects/2026-03/0-410/batch/read
      security:
      - oauth2:
        - crm.objects.courses.read
      x-hubspot-user-level-auth:
        internalOnly: false
  /crm/objects/2026-03/0-410/batch/update:
    post:
      tags:
      - Batch
      summary: Batch update courses
      description: Update a batch of objects
      operationId: post-/crm/objects/2026-03/0-410/batch/update
      security:
      - oauth2:
        - crm.objects.courses.write
      x-hubspot-user-level-auth:
        internalOnly: false
  /crm/objects/2026-03/0-410/batch/upsert:
    post:
      tags:
      - Batch
      summary: Upsert courses
      description: Create or update records identified by a unique property value as specified by the
        `idProperty` query param. `idProperty` query param refers to a property whose values are unique
        for the object.
      operationId: post-/crm/objects/2026-03/0-410/batch/upsert
      security:
      - oauth2:
        - crm.objects.courses.write
      x-hubspot-user-level-auth:
        internalOnly: false
  /crm/objects/2026-03/0-410/search:
    post:
      tags:
      - Search
      summary: Search for courses
      description: Fetch objects using a search query
      operationId: post-/crm/objects/2026-03/0-410/search
      security:
      - oauth2:
        - crm.objects.courses.read
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
      x-hubspot-user-level-auth:
        internalOnly: false
  /crm/objects/2026-03/0-410/{courseId}:
    get:
      tags:
      - Basic
      summary: Retrieve a course
      description: Read an Object identified by `{courseId}`. `{courseId}` refers to the internal object
        ID by default, or optionally any unique property value as specified by the `idProperty` query
        param.  Control what is returned via the `properties` query param.
      operationId: get-/crm/objects/2026-03/0-410/{courseId}
      security:
      - oauth2:
        - crm.objects.courses.read
      x-hubspot-user-level-auth:
        internalOnly: false
    delete:
      tags:
      - Basic
      summary: Archive a course
      description: Move an Object identified by `{courseId}` to the recycling bin.
      operationId: delete-/crm/objects/2026-03/0-410/{courseId}
      security:
      - oauth2:
        - crm.objects.courses.write
      x-hubspot-user-level-auth:
        internalOnly: false
    patch:
      tags:
      - Basic
      summary: Update a course
      description: Perform a partial update of an Object identified by `{courseId}`or optionally a unique
        property value as specified by the `idProperty` query param. `{courseId}` refers to the internal
        object ID by default, and the `idProperty` query param refers to a property whose values are unique
        for the object. Provided property values will be overwritten. Read-only and non-existent properties
        will result in an error. Properties values can be cleared by passing an empty string.
      operationId: patch-/crm/objects/2026-03/0-410/{courseId}
      security:
      - oauth2:
        - crm.objects.courses.write
      x-hubspot-user-level-auth:
        internalOnly: false
  /crm/objects/2026-03/courses/merge:
    post:
      tags:
      - Advanced
      summary: Merge two courses
      description: Merge two courses.
      operationId: post-/crm/objects/2026-03/courses/merge
      security:
      - oauth2:
        - crm.objects.courses.write
      x-hubspot-user-level-auth:
        internalOnly: false
components:
  securitySchemes:
    developer_hapikey:
      type: apiKey
      name: hapikey
      in: query
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            crm.objects.commercepayments.read: ''
            crm.objects.courses.read: ''
            crm.objects.courses.write: ''
            oauth: ''
            oauth-access: ''
    private_apps:
      type: apiKey
      name: private-app
      in: header
    private_apps_legacy:
      type: apiKey
      name: private-app-legacy
      in: header
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
  commerce: FREE
  crmHub: FREE
  dataHub: FREE
