openapi: 3.2.0
info:
  title: CRM Associations Schema Limits API
  description: Basepom for all HubSpot Projects
  version: 2026-09
  x-hubspot-product-tier-requirements:
    marketing: FREE
    sales: FREE
    service: FREE
    cms: FREE
    commerce: FREE
    crmHub: FREE
    dataHub: FREE
servers:
- url: https://api.hubapi.com
tags:
- name: Limits
paths:
  /crm/associations/2026-09/definitions/configurations/all:
    get:
      tags:
      - Limits
      summary: Retrieve all association limits
      description: Retrieve all configured association limits between objects, which include details about how different CRM object types are associated with each other.
      operationId: get-/crm/associations/2026-09/definitions/configurations/all_getPage
      security:
      - oauth2:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.tickets.sensitive.read
      - oauth2:
        - crm.objects.orders.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.tasks.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.highly_sensitive.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.sensitive.write
      - oauth2:
        - media_bridge.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.commercepayments.write
      - oauth2:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.calls.read
      - oauth2:
        - crm.objects.meetings.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.partner-services.read
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.partner-services.write
      - oauth2:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.projects.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.tickets.highly_sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.products.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - crm.objects.contacts.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.projects.highly_sensitive.read
      - oauth2:
        - tickets.sensitive.v2
      - oauth2:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - oauth2:
        - crm.objects.projects.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.projects.sensitive.read
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.projects.write
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.projects.sensitive.write
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.emails.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.notes.read
      - oauth2:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.products.read
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/associations/2026-09/definitions/configurations/{fromObjectType}/{toObjectType}:
    get:
      tags:
      - Limits
      summary: Retrieve association limits
      description: Retrieve the configuration details for associations between two specified CRM object types. Use this endpoint to understand limits that have been set for specific association types.
      operationId: get-/crm/associations/2026-09/definitions/configurations/{fromObjectType}/{toObjectType}_getPageBetweenTwoObjectTypes
      security:
      - oauth2:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.tickets.sensitive.read
      - oauth2:
        - crm.objects.orders.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.tasks.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.highly_sensitive.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.sensitive.write
      - oauth2:
        - media_bridge.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.commercepayments.write
      - oauth2:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.calls.read
      - oauth2:
        - crm.objects.meetings.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.partner-services.read
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.partner-services.write
      - oauth2:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.projects.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.tickets.highly_sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.products.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - crm.objects.contacts.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.projects.highly_sensitive.read
      - oauth2:
        - tickets.sensitive.v2
      - oauth2:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - oauth2:
        - crm.objects.projects.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.projects.sensitive.read
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.projects.write
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.projects.sensitive.write
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.emails.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.notes.read
      - oauth2:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.products.read
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/associations/2026-09/definitions/configurations/{fromObjectType}/{toObjectType}/batch/create:
    post:
      tags:
      - Limits
      summary: Configure association limits
      description: Batch configure association limits between two object types.
      operationId: post-/crm/associations/2026-09/definitions/configurations/{fromObjectType}/{toObjectType}/batch/create_batchCreate
      security:
      - oauth2:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.tickets.sensitive.read
      - oauth2:
        - crm.objects.orders.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.tasks.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.highly_sensitive.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.sensitive.write
      - oauth2:
        - media_bridge.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.commercepayments.write
      - oauth2:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.calls.read
      - oauth2:
        - crm.objects.meetings.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.partner-services.read
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.partner-services.write
      - oauth2:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.projects.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.tickets.highly_sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.products.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - crm.objects.contacts.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.projects.highly_sensitive.read
      - oauth2:
        - tickets.sensitive.v2
      - oauth2:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - oauth2:
        - crm.objects.projects.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.projects.sensitive.read
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.projects.write
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.projects.sensitive.write
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.emails.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.notes.read
      - oauth2:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.products.read
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/associations/2026-09/definitions/configurations/{fromObjectType}/{toObjectType}/batch/purge:
    post:
      tags:
      - Limits
      summary: Remove association limits
      description: Batch delete limits that have been defined for association types between two object types.
      operationId: post-/crm/associations/2026-09/definitions/configurations/{fromObjectType}/{toObjectType}/batch/purge_batchRemove
      security:
      - oauth2:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.tickets.sensitive.read
      - oauth2:
        - crm.objects.orders.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.tasks.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.highly_sensitive.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.sensitive.write
      - oauth2:
        - media_bridge.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.commercepayments.write
      - oauth2:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.calls.read
      - oauth2:
        - crm.objects.meetings.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.partner-services.read
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.partner-services.write
      - oauth2:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.projects.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.tickets.highly_sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.products.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - crm.objects.contacts.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.projects.highly_sensitive.read
      - oauth2:
        - tickets.sensitive.v2
      - oauth2:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - oauth2:
        - crm.objects.projects.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.projects.sensitive.read
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.projects.write
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.projects.sensitive.write
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.emails.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.notes.read
      - oauth2:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.products.read
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
  /crm/associations/2026-09/definitions/configurations/{fromObjectType}/{toObjectType}/batch/update:
    post:
      tags:
      - Limits
      summary: Update association limits
      description: Batch update association limits that have been configured between two object types.
      operationId: post-/crm/associations/2026-09/definitions/configurations/{fromObjectType}/{toObjectType}/batch/update_batchUpdate
      security:
      - oauth2:
        - crm.objects.deals.read
      - oauth2:
        - crm.objects.subscriptions.read
      - oauth2:
        - crm.objects.services.read
      - oauth2:
        - crm.objects.tickets.sensitive.read
      - oauth2:
        - crm.objects.orders.read
      - oauth2:
        - crm.objects.listings.write
      - oauth2:
        - crm.objects.custom.read
      - oauth2:
        - crm.objects.companies.write
      - oauth2:
        - crm.objects.tasks.read
      - oauth2:
        - crm.objects.custom.sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.read
      - oauth2:
        - crm.objects.contacts.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.appointments.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.highly_sensitive.read
      - oauth2:
        - crm.objects.companies.sensitive.read.v2
      - oauth2:
        - crm.objects.tickets.sensitive.write
      - oauth2:
        - media_bridge.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.contacts.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.commercepayments.write
      - oauth2:
        - crm.objects.invoices.write
      - oauth2:
        - crm.objects.contacts.sensitive.write.v2
      - oauth2:
        - crm.objects.users.write
      - oauth2:
        - crm.objects.calls.read
      - oauth2:
        - crm.objects.meetings.read
      - oauth2:
        - crm.objects.custom.sensitive.read.v2
      - oauth2:
        - crm.objects.users.read
      - oauth2:
        - crm.objects.partner-services.read
      - oauth2:
        - crm.objects.orders.write
      - oauth2:
        - crm.objects.partner-services.write
      - oauth2:
        - crm.objects.appointments.write
      - oauth2:
        - crm.objects.projects.highly_sensitive.write
      - oauth2:
        - crm.objects.carts.write
      - oauth2:
        - crm.objects.tickets.highly_sensitive.write
      - oauth2:
        - tickets
      - oauth2:
        - crm.objects.commercepayments.read
      - oauth2:
        - crm.objects.products.write
      - oauth2:
        - crm.objects.services.write
      - oauth2:
        - crm.objects.subscriptions.write
      - oauth2:
        - crm.objects.deals.sensitive.write.v2
      - oauth2:
        - crm.objects.contacts.read
      - oauth2:
        - crm.objects.appointments.sensitive.write.v2
      - oauth2:
        - crm.objects.invoices.read
      - oauth2:
        - crm.objects.projects.highly_sensitive.read
      - oauth2:
        - tickets.sensitive.v2
      - oauth2:
        - crm.objects.custom.write
      - oauth2:
        - crm.objects.deals.write
      - oauth2:
        - e-commerce
      - oauth2:
        - crm.objects.appointments.read
      - oauth2:
        - crm.objects.companies.sensitive.write.v2
      - oauth2:
        - crm.objects.projects.read
      - oauth2:
        - crm.objects.deals.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.custom.highly_sensitive.read.v2
      - oauth2:
        - crm.objects.companies.highly_sensitive.write.v2
      - oauth2:
        - crm.objects.goals.write
      - oauth2:
        - crm.objects.line_items.write
      - oauth2:
        - crm.objects.projects.sensitive.read
      - oauth2:
        - crm.objects.contacts.write
      - oauth2:
        - crm.objects.goals.read
      - oauth2:
        - crm.objects.line_items.read
      - oauth2:
        - crm.objects.partner-clients.write
      - oauth2:
        - crm.objects.projects.write
      - oauth2:
        - crm.objects.deals.sensitive.read.v2
      - oauth2:
        - crm.objects.projects.sensitive.write
      - oauth2:
        - crm.objects.quotes.write
      - oauth2:
        - tickets.highly_sensitive.v2
      - oauth2:
        - crm.objects.leads.read
      - oauth2:
        - crm.objects.leads.write
      - oauth2:
        - crm.objects.carts.read
      - oauth2:
        - crm.objects.emails.read
      - oauth2:
        - crm.objects.quotes.read
      - oauth2:
        - crm.objects.courses.write
      - oauth2:
        - crm.objects.partner-clients.read
      - oauth2:
        - crm.objects.notes.read
      - oauth2:
        - crm.objects.courses.read
      - oauth2:
        - crm.objects.listings.read
      - oauth2:
        - crm.objects.contacts.sensitive.read.v2
      - oauth2:
        - crm.objects.products.read
      x-hubspot-rate-limit-exemptions:
      - ten-secondly
components:
  securitySchemes:
    developer_hapikey:
      type: apiKey
      name: hapikey
      in: query
    oauth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          tokenUrl: https://api.hubapi.com/oauth/v1/token
          scopes:
            crm.objects.appointments.read: ''
            crm.objects.appointments.sensitive.read.v2: ''
            crm.objects.appointments.sensitive.write.v2: ''
            crm.objects.appointments.write: ''
            crm.objects.calls.read: ''
            crm.objects.carts.read: ''
            crm.objects.carts.write: ''
            crm.objects.commercepayments.read: ''
            crm.objects.commercepayments.write: ''
            crm.objects.companies.highly_sensitive.read.v2: ''
            crm.objects.companies.highly_sensitive.write.v2: ''
            crm.objects.companies.read: ''
            crm.objects.companies.sensitive.read.v2: ''
            crm.objects.companies.sensitive.write.v2: ''
            crm.objects.companies.write: ''
            crm.objects.contacts.highly_sensitive.read.v2: ''
            crm.objects.contacts.highly_sensitive.write.v2: ''
            crm.objects.contacts.read: ''
            crm.objects.contacts.sensitive.read.v2: ''
            crm.objects.contacts.sensitive.write.v2: ''
            crm.objects.contacts.write: ''
            crm.objects.courses.read: ''
            crm.objects.courses.write: ''
            crm.objects.custom.highly_sensitive.read.v2: ''
            crm.objects.custom.highly_sensitive.write.v2: ''
            crm.objects.custom.read: ''
            crm.objects.custom.sensitive.read.v2: ''
            crm.objects.custom.sensitive.write.v2: ''
            crm.objects.custom.write: ''
            crm.objects.deals.highly_sensitive.read.v2: ''
            crm.objects.deals.highly_sensitive.write.v2: ''
            crm.objects.deals.read: ''
            crm.objects.deals.sensitive.read.v2: ''
            crm.objects.deals.sensitive.write.v2: ''
            crm.objects.deals.write: ''
            crm.objects.emails.read: ''
            crm.objects.goals.read: ''
            crm.objects.goals.write: ''
            crm.objects.invoices.read: ''
            crm.objects.invoices.write: ''
            crm.objects.leads.read: ''
            crm.objects.leads.write: ''
            crm.objects.line_items.read: ''
            crm.objects.line_items.write: ''
            crm.objects.listings.read: ''
            crm.objects.listings.write: ''
            crm.objects.meetings.read: ''
            crm.objects.notes.read: ''
            crm.objects.orders.read: ''
            crm.objects.orders.write: ''
            crm.objects.partner-clients.read: ''
            crm.objects.partner-clients.write: ''
            crm.objects.partner-services.read: ''
            crm.objects.partner-services.write: ''
            crm.objects.products.read: ''
            crm.objects.products.write: ''
            crm.objects.projects.highly_sensitive.read: ''
            crm.objects.projects.highly_sensitive.write: ''
            crm.objects.projects.read: ''
            crm.objects.projects.sensitive.read: ''
            crm.objects.projects.sensitive.write: ''
            crm.objects.projects.write: ''
            crm.objects.quotes.read: ''
            crm.objects.quotes.write: ''
            crm.objects.services.read: ''
            crm.objects.services.write: ''
            crm.objects.subscriptions.read: ''
            crm.objects.subscriptions.write: ''
            crm.objects.tasks.read: ''
            crm.objects.tickets.highly_sensitive.read: ''
            crm.objects.tickets.highly_sensitive.write: ''
            crm.objects.tickets.sensitive.read: ''
            crm.objects.tickets.sensitive.write: ''
            crm.objects.users.read: ''
            crm.objects.users.write: ''
            e-commerce: ''
            media_bridge.read: ''
            tickets: ''
            tickets.highly_sensitive.v2: ''
            tickets.sensitive.v2: ''
    private_apps:
      type: apiKey
      name: private-app
      in: header
    private_apps_legacy:
      type: apiKey
      name: private-app-legacy
      in: header
x-hubspot-available-client-libraries:
- Node
- Python
- Ruby
- PHP
x-hubspot-product-tier-requirements:
  marketing: FREE
  sales: FREE
  service: FREE
  cms: FREE
  commerce: FREE
  crmHub: FREE
  dataHub: FREE
