{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Commerce Price Books",
    "description" : "Basepom for all HubSpot Projects",
    "version" : "2026-09",
    "x-hubspot-product-tier-requirements" : {
      "marketing" : "FREE",
      "sales" : "FREE",
      "service" : "FREE",
      "cms" : "FREE",
      "commerce" : "FREE",
      "crmHub" : "FREE",
      "dataHub" : "FREE"
    }
  },
  "servers" : [ {
    "url" : "https://api.hubapi.com"
  } ],
  "tags" : [ {
    "name" : "Advanced"
  }, {
    "name" : "Basic"
  }, {
    "name" : "Batch"
  }, {
    "name" : "Items"
  } ],
  "paths" : {
    "/commerce/price-books/2026-09/price-books" : {
      "get" : {
        "tags" : [ "Advanced" ],
        "summary" : "Retrieve price books",
        "description" : "Retrieve a list of price books available in your HubSpot account. This endpoint supports pagination and can return archived price books if specified. It is useful for accessing and managing pricing information across different products and services.",
        "operationId" : "get-/commerce/price-books/2026-09/price-books_/commerce/price-books/2026-09-beta/price-books",
        "security" : [ {
          "oauth2" : [ "price-book-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Create price book",
        "description" : "Create a new price book in your HubSpot account. This endpoint allows you to define custom properties, a name, and supported currencies for the price book. A successful request will return the URL of the newly created resource.",
        "operationId" : "post-/commerce/price-books/2026-09/price-books",
        "security" : [ {
          "oauth2" : [ "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}" : {
      "get" : {
        "tags" : [ "Basic" ],
        "summary" : "Retrieve price book",
        "description" : "Retrieve a specific price book by its unique identifier in your HubSpot account. This endpoint allows you to access detailed information about a price book, including its status and supported currencies. It can be useful for managing and reviewing pricing strategies within your commerce system.",
        "operationId" : "get-/commerce/price-books/2026-09/price-books/{priceBookId}",
        "security" : [ {
          "oauth2" : [ "price-book-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Basic" ],
        "summary" : "Delete price book",
        "description" : "Delete a specific price book from your HubSpot account using its unique identifier. This operation will permanently remove the price book and its associated data, making it unavailable for future use.",
        "operationId" : "delete-/commerce/price-books/2026-09/price-books/{priceBookId}",
        "security" : [ {
          "oauth2" : [ "price-book-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Basic" ],
        "summary" : "Update price book",
        "description" : "Update an existing price book in your HubSpot account. This operation allows you to modify details such as the name, description, supported currencies, and custom properties of a price book. It is useful for keeping your price book information up to date with the latest changes.",
        "operationId" : "patch-/commerce/price-books/2026-09/price-books/{priceBookId}",
        "security" : [ {
          "oauth2" : [ "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}/activate" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Activate price book",
        "description" : "Activate a specific price book in your HubSpot account. This operation changes the status of the price book to active, allowing it to be used in transactions and other operations. Ensure that the price book ID is correct before activation.",
        "operationId" : "post-/commerce/price-books/2026-09/price-books/{priceBookId}/activate",
        "security" : [ {
          "oauth2" : [ "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}/deactivate" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Deactivate price book",
        "description" : "Deactivate a specific price book in your HubSpot account. This action changes the status of the price book to inactive, making it unavailable for use in transactions. Use this endpoint when you need to temporarily or permanently disable a price book without deleting it.",
        "operationId" : "post-/commerce/price-books/2026-09/price-books/{priceBookId}/deactivate",
        "security" : [ {
          "oauth2" : [ "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}/items" : {
      "get" : {
        "tags" : [ "Items" ],
        "summary" : "List price book items",
        "description" : "Retrieve a list of items associated with a specific price book in your HubSpot account. This endpoint allows you to paginate through the items and specify which properties to include in the response. It is useful for managing and viewing the details of products linked to a particular price book.",
        "operationId" : "get-/commerce/price-books/2026-09/price-books/{priceBookId}/items_/commerce/price-books/2026-09-beta/price-books/{priceBookId}/items",
        "security" : [ {
          "oauth2" : [ "price-book-read" ]
        } ]
      },
      "post" : {
        "tags" : [ "Items" ],
        "summary" : "Add price book items",
        "description" : "Add new items to a specified price book in your HubSpot account. This endpoint allows you to associate products with a price book by providing the necessary product details. It is useful for managing and updating the contents of your price books efficiently.",
        "operationId" : "post-/commerce/price-books/2026-09/price-books/{priceBookId}/items_/commerce/price-books/2026-09-beta/price-books/{priceBookId}/items",
        "security" : [ {
          "oauth2" : [ "inbounddb-product-library-read", "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}/items/batch/archive" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch archive price book items",
        "description" : "Archive multiple items within a specified price book in a single batch operation. This endpoint is useful for managing large sets of price book items that need to be archived simultaneously, streamlining the process and reducing the number of individual requests.",
        "operationId" : "post-/commerce/price-books/2026-09/price-books/{priceBookId}/items/batch/archive_/commerce/price-books/2026-09-beta/price-books/{priceBookId}/items/batch/archive",
        "security" : [ {
          "oauth2" : [ "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}/items/batch/create" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch create price book items",
        "description" : "Create multiple items in a specified price book in a single batch operation. This endpoint is useful for efficiently adding a large number of items to a price book, reducing the need for multiple individual requests. The operation returns a batch response indicating the success or failure of each item creation.",
        "operationId" : "post-/commerce/price-books/2026-09/price-books/{priceBookId}/items/batch/create_/commerce/price-books/2026-09-beta/price-books/{priceBookId}/items/batch/create",
        "security" : [ {
          "oauth2" : [ "inbounddb-product-library-read", "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}/items/batch/update" : {
      "post" : {
        "tags" : [ "Batch" ],
        "summary" : "Batch update price book items",
        "description" : "Update multiple items in a specified price book in a single batch operation. This endpoint allows for efficient updates of price book items, making it useful for managing large sets of data within a price book. The operation returns a batch response indicating the success or failure of each item update.",
        "operationId" : "post-/commerce/price-books/2026-09/price-books/{priceBookId}/items/batch/update_/commerce/price-books/2026-09-beta/price-books/{priceBookId}/items/batch/update",
        "security" : [ {
          "oauth2" : [ "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}/items/{priceBookItemId}" : {
      "get" : {
        "tags" : [ "Items" ],
        "summary" : "Retrieve price book item",
        "description" : "Retrieve a specific item from a price book using its unique identifiers. This endpoint allows you to access detailed information about a particular item within a specified price book, including its properties and archived status if applicable.",
        "operationId" : "get-/commerce/price-books/2026-09/price-books/{priceBookId}/items/{priceBookItemId}_/commerce/price-books/2026-09-beta/price-books/{priceBookId}/items/{priceBookItemId}",
        "security" : [ {
          "oauth2" : [ "price-book-read" ]
        } ]
      },
      "delete" : {
        "tags" : [ "Items" ],
        "summary" : "Delete price book item",
        "description" : "Remove a specific item from a price book in your HubSpot account. This operation is irreversible and will permanently delete the item identified by the given priceBookItemId from the price book specified by priceBookId.",
        "operationId" : "delete-/commerce/price-books/2026-09/price-books/{priceBookId}/items/{priceBookItemId}",
        "security" : [ {
          "oauth2" : [ "price-book-write" ]
        } ]
      },
      "patch" : {
        "tags" : [ "Items" ],
        "summary" : "Update price book item",
        "description" : "Update a specific item within a price book in your HubSpot account. This operation allows you to modify details such as pricing, billing frequency, and custom properties for the specified item. Ensure that the item is identified correctly by its unique priceBookId and priceBookItemId.",
        "operationId" : "patch-/commerce/price-books/2026-09/price-books/{priceBookId}/items/{priceBookItemId}",
        "security" : [ {
          "oauth2" : [ "inbounddb-product-library-read", "price-book-write" ]
        } ]
      }
    },
    "/commerce/price-books/2026-09/price-books/{priceBookId}/validate" : {
      "post" : {
        "tags" : [ "Basic" ],
        "summary" : "Validate price book",
        "description" : "Validate a specific price book in your HubSpot account. This endpoint checks the integrity and correctness of the price book identified by the given priceBookId. Use this to ensure that the price book meets all necessary criteria before proceeding with further operations.",
        "operationId" : "post-/commerce/price-books/2026-09/price-books/{priceBookId}/validate",
        "security" : [ {
          "oauth2" : [ "price-book-read" ]
        } ]
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "developer_hapikey" : {
        "type" : "apiKey",
        "name" : "hapikey",
        "in" : "query"
      },
      "oauth2" : {
        "type" : "oauth2",
        "flows" : {
          "authorizationCode" : {
            "authorizationUrl" : "https://app.hubspot.com/oauth/authorize",
            "tokenUrl" : "https://api.hubapi.com/oauth/v1/token",
            "scopes" : {
              "crm.objects.products.read" : "",
              "price-book-read" : "",
              "price-book-write" : ""
            }
          }
        }
      },
      "private_apps" : {
        "type" : "apiKey",
        "name" : "private-app",
        "in" : "header"
      },
      "private_apps_legacy" : {
        "type" : "apiKey",
        "name" : "private-app-legacy",
        "in" : "header"
      }
    }
  },
  "x-hubspot-product-tier-requirements" : {
    "marketing" : "FREE",
    "sales" : "FREE",
    "service" : "FREE",
    "cms" : "FREE",
    "commerce" : "FREE",
    "crmHub" : "FREE",
    "dataHub" : "FREE"
  }
}